# .github/workflows/deploy.yml
name: Build and Deploy Portfolio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm init -y
        npm install --save-dev html-minifier-terser clean-css-cli terser

    - name: Build Tailwind CSS
      run: |
        npm install --save-dev tailwindcss @tailwindcss/cli daisyui
        npx tailwindcss -i app.css -o styles/output.css --minify

    - name: Prepare build directory
      run: |
        mkdir -p build
        rsync -av --exclude=build --exclude=node_modules --exclude=.git --exclude=.github \
          --exclude="app.css" --exclude="tailwind.config.js" \
          . build/

    - name: Minify HTML files
      run: |
        find build -name "*.html" -type f -exec npx html-minifier-terser \
          --collapse-whitespace \
          --remove-comments \
          --remove-optional-tags \
          --remove-redundant-attributes \
          --remove-script-type-attributes \
          --remove-tag-whitespace \
          --use-short-doctype \
          --minify-css true \
          --minify-js true \
          {} --output {} \;

    - name: Minify CSS files (excluding output.css)
      run: |
        find build -name "*.css" -type f ! -name "output.css" \
          -exec npx cleancss -o {} {} \;

    - name: Minify JavaScript files
      run: |
        find build -name "*.js" -type f -exec npx terser {} -o {} --compress --mangle \;

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        force_orphan: true
